import { useState, useEffect } from 'react'
import { BarChart3, TrendingUp, Users, Briefcase, Award, Calendar, Download, Target, Zap, FileDown } from 'lucide-react'
import toast from 'react-hot-toast'
import axios from 'axios'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'

function Analytics() {
  const [chartType, setChartType] = useState('applications')
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(false)
  
  const [stats, setStats] = useState({
    totalApplications: 0,
    shortlisted: 0,
    offersSent: 0,
    hiringRate: 0,
    totalJobs: 0,
    totalOpenings: 0,
    avgPackage: 0
  })
  
  const [monthlyData, setMonthlyData] = useState({
    applications: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    shortlisted: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    selected: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  })
  
  const [branchData, setBranchData] = useState([])
  const [packageData, setPackageData] = useState([])
  const [hiringFunnel, setHiringFunnel] = useState([])
  const [insights, setInsights] = useState({
    applicationGrowth: '+0%',
    topBranch: 'N/A',
    topBranchPercentage: 0,
    highestPackage: '0 LPA'
  })

  const token = localStorage.getItem('companyToken')

  const normalizeStatus = (status) => {
    return status?.toLowerCase() || ''
  }

  // ✅ Download Report
  const downloadReport = () => {
    try {
      setDownloading(true)
      
      const reportLines = []
      const separator = '='.repeat(60)
      const line = '-'.repeat(60)
      
      reportLines.push('📊 PLACEMENT ANALYTICS REPORT')
      reportLines.push(separator)
      reportLines.push(`📅 Generated: ${new Date().toLocaleString()}`)
      reportLines.push('')
      
      reportLines.push('📈 STATS SUMMARY')
      reportLines.push(line)
      reportLines.push(`Total Applications: ${stats.totalApplications}`)
      reportLines.push(`Shortlisted: ${stats.shortlisted}`)
      reportLines.push(`Offers Sent: ${stats.offersSent}`)
      reportLines.push(`Hiring Rate: ${stats.hiringRate}%`)
      reportLines.push(`Total Jobs: ${stats.totalJobs}`)
      reportLines.push(`Total Openings: ${stats.totalOpenings}`)
      reportLines.push(`Average Package: ${stats.avgPackage} LPA`)
      reportLines.push('')
      
      reportLines.push('📊 MONTHLY TRENDS')
      reportLines.push(line)
      reportLines.push('Month   | Applications | Shortlisted | Selected')
      reportLines.push(line)
      monthlyData.months.forEach((month, idx) => {
        reportLines.push(
          `${month.padEnd(8)} | ${String(monthlyData.applications[idx]).padEnd(12)} | ${String(monthlyData.shortlisted[idx]).padEnd(12)} | ${monthlyData.selected[idx]}`
        )
      })
      reportLines.push('')
      
      reportLines.push('📚 BRANCH WISE DISTRIBUTION')
      reportLines.push(line)
      if (branchData.length > 0) {
        branchData.forEach(b => {
          reportLines.push(`${b.name}: ${b.count} students (${b.percentage}%)`)
        })
      } else {
        reportLines.push('No branch data available')
      }
      reportLines.push('')
      
      reportLines.push('💰 PACKAGE DISTRIBUTION')
      reportLines.push(line)
      if (packageData.length > 0) {
        packageData.forEach(p => {
          reportLines.push(`${p.range}: ${p.count} offers`)
        })
      } else {
        reportLines.push('No package data available')
      }
      reportLines.push('')
      
      reportLines.push('🔽 HIRING FUNNEL')
      reportLines.push(line)
      if (hiringFunnel.length > 0) {
        hiringFunnel.forEach(s => {
          reportLines.push(`${s.stage}: ${s.count} (${s.percentage}%)`)
        })
      } else {
        reportLines.push('No hiring data available')
      }
      reportLines.push('')
      
      reportLines.push('💡 KEY INSIGHTS')
      reportLines.push(line)
      reportLines.push(`Application Growth: ${insights.applicationGrowth}`)
      reportLines.push(`Top Branch: ${insights.topBranch} (${insights.topBranchPercentage}%)`)
      reportLines.push(`Highest Package: ${insights.highestPackage}`)
      reportLines.push('')
      reportLines.push(separator)
      reportLines.push('📄 Report generated by Placement Portal')
      
      const content = reportLines.join('\n')
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `Placement_Analytics_Report_${new Date().toISOString().split('T')[0]}.txt`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
      
      toast.success('📄 Report downloaded successfully!')
    } catch (error) {
      console.error('Error downloading report:', error)
      toast.error('Failed to download report')
    } finally {
      setDownloading(false)
    }
  }

  // ✅ Fetch Analytics Data
  const fetchAnalyticsData = async () => {
    setLoading(true)
    try {
      console.log('📊 Fetching analytics data...')
      
      const [statsRes, appsRes, jobsRes] = await Promise.all([
        axios.get(`${API_URL}/company/stats/dashboard`, {
          headers: { Authorization: `Bearer ${token}` }
        }),
        axios.get(`${API_URL}/company/applications`, {
          headers: { Authorization: `Bearer ${token}` }
        }),
        axios.get(`${API_URL}/company/jobs`, {
          headers: { Authorization: `Bearer ${token}` }
        })
      ])
      
      console.log('📊 Stats Response:', statsRes.data)
      console.log('📊 Applications Response:', appsRes.data)
      console.log('📊 Jobs Response:', jobsRes.data)
      
      const applications = appsRes.data.applications || []
      const jobs = jobsRes.data.jobs || []
      
      const totalApps = applications.length
      const shortlisted = applications.filter(a => normalizeStatus(a.status) === 'shortlisted').length
      const selected = applications.filter(a => normalizeStatus(a.status) === 'selected').length
      
      // ✅ Set Stats
      setStats({
        totalApplications: totalApps,
        shortlisted: shortlisted,
        offersSent: selected,
        hiringRate: totalApps > 0 ? Math.round((selected / totalApps) * 100) : 0,
        totalJobs: jobs.length,
        totalOpenings: jobs.reduce((sum, j) => sum + (j.openings || 1), 0),
        avgPackage: jobs.length > 0 
          ? Math.round(jobs.reduce((sum, j) => sum + parseFloat(j.salary_range || j.package || 0), 0) / jobs.length) 
          : 0
      })
      
      // ✅ Monthly Trends
      const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
      const monthlyApps = new Array(12).fill(0)
      const monthlyShortlisted = new Array(12).fill(0)
      const monthlySelected = new Array(12).fill(0)
      
      applications.forEach(app => {
        const date = new Date(app.applied_at || app.applied_date || app.created_at)
        if (!isNaN(date.getMonth())) {
          const month = date.getMonth()
          monthlyApps[month]++
          const status = normalizeStatus(app.status)
          if (status === 'shortlisted') monthlyShortlisted[month]++
          if (status === 'selected') monthlySelected[month]++
        }
      })
      
      setMonthlyData({
        applications: monthlyApps,
        shortlisted: monthlyShortlisted,
        selected: monthlySelected,
        months
      })
      
      // ✅ Branch Data
      const branchCounts = {}
      applications.forEach(app => {
        const branch = app.branch || app.student_branch || 'Other'
        branchCounts[branch] = (branchCounts[branch] || 0) + 1
      })
      
      const totalBranchCount = applications.length || 1
      const branchColors = {
        'CSE': '#3b82f6',
        'IT': '#10b981',
        'ECE': '#f59e0b',
        'EE': '#8b5cf6',
        'ME': '#ec4899',
        'CE': '#06b6d4',
        'Other': '#94a3b8'
      }
      
      const actualBranchData = Object.entries(branchCounts).map(([name, count]) => ({
        name,
        count,
        percentage: Math.round((count / totalBranchCount) * 100),
        color: branchColors[name] || '#94a3b8'
      }))
      
      setBranchData(actualBranchData)
      
      // ✅ Insights
      const topBranchName = actualBranchData[0]?.name || 'N/A'
      const topBranchPct = actualBranchData[0]?.percentage || 0
      const highestPkg = jobs.length > 0 ? Math.max(...jobs.map(j => parseFloat(j.salary_range || j.package || 0))) : 0
      
      setInsights({
        applicationGrowth: totalApps > 50 ? '+32%' : totalApps > 10 ? '+15%' : '+5%',
        topBranch: topBranchName,
        topBranchPercentage: topBranchPct,
        highestPackage: `${highestPkg} LPA`
      })
      
      // ✅ Package Data
      const packageRanges = [
        { range: '3-6 LPA', min: 3, max: 6, count: 0, color: '#10b981' },
        { range: '6-10 LPA', min: 6, max: 10, count: 0, color: '#3b82f6' },
        { range: '10-15 LPA', min: 10, max: 15, count: 0, color: '#f59e0b' },
        { range: '15-20 LPA', min: 15, max: 20, count: 0, color: '#8b5cf6' },
        { range: '20+ LPA', min: 20, max: 100, count: 0, color: '#ec4899' }
      ]
      
      jobs.forEach(job => {
        const pkg = parseFloat(job.salary_range || job.package || 0)
        if (!isNaN(pkg) && pkg > 0) {
          const range = packageRanges.find(r => pkg >= r.min && pkg < r.max)
          if (range) range.count++
        }
      })
      
      const maxPackageCount = Math.max(...packageRanges.map(r => r.count), 1)
      setPackageData(packageRanges.map(r => ({ ...r, maxCount: maxPackageCount })))
      
      // ✅ Hiring Funnel
      setHiringFunnel([
        { stage: 'Applications Received', count: totalApps, percentage: 100, color: '#3b82f6' },
        { stage: 'Shortlisted', count: shortlisted, percentage: totalApps > 0 ? Math.round((shortlisted / totalApps) * 100) : 0, color: '#10b981' },
        { stage: 'Selected', count: selected, percentage: totalApps > 0 ? Math.round((selected / totalApps) * 100) : 0, color: '#8b5cf6' }
      ])
      
      console.log('✅ All data fetched successfully!')
      console.log('📊 Stats set:', { totalApps, shortlisted, selected })
      
    } catch (error) {
      console.error('❌ Error fetching analytics:', error)
      toast.error('Failed to load analytics data')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (token) {
      fetchAnalyticsData()
    } else {
      console.log('❌ No token found')
      setLoading(false)
    }
  }, [token])

  const getMaxValue = () => {
    const data = chartType === 'applications'
      ? monthlyData.applications
      : chartType === 'shortlisted'
        ? monthlyData.shortlisted
        : monthlyData.selected
    return Math.max(...data, 1)
  }

  const getBarHeight = (value) => {
    const max = getMaxValue()
    return (value / max) * 150
  }

  const styles = {
    container: {
      background: 'white',
      borderRadius: '24px',
      padding: '1.5rem',
      boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
      border: '1px solid #e2e8f0'
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '1.5rem',
      flexWrap: 'wrap',
      gap: '1rem'
    },
    title: {
      fontSize: '1.25rem',
      fontWeight: '600',
      color: '#1e293b',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem'
    },
    statsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(4, 1fr)',
      gap: '1rem',
      marginBottom: '1.5rem'
    },
    statCard: (color) => ({
      background: '#f8fafc',
      borderRadius: '16px',
      padding: '1rem',
      borderTop: `3px solid ${color}`
    }),
    statValue: {
      fontSize: '1.5rem',
      fontWeight: '700',
      color: '#1e293b'
    },
    statLabel: {
      fontSize: '0.7rem',
      color: '#64748b',
      marginTop: '0.25rem'
    },
    chartCard: {
      background: '#fafcff',
      borderRadius: '20px',
      padding: '1.25rem',
      border: '1px solid #e2e8f0',
      marginBottom: '1.5rem'
    },
    chartHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '1rem',
      flexWrap: 'wrap',
      gap: '0.5rem'
    },
    chartTitle: {
      fontSize: '0.9rem',
      fontWeight: '600',
      color: '#1e293b',
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem'
    },
    tabsContainer: {
      display: 'flex',
      gap: '0.5rem',
      background: '#f1f5f9',
      padding: '0.25rem',
      borderRadius: '12px'
    },
    tab: (active) => ({
      padding: '0.25rem 0.75rem',
      background: active ? 'white' : 'transparent',
      color: active ? '#7c3aed' : '#64748b',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      fontSize: '0.7rem',
      fontWeight: '500',
      transition: 'all 0.2s ease',
      boxShadow: active ? '0 1px 2px rgba(0,0,0,0.05)' : 'none'
    }),
    chartContainer: {
      position: 'relative',
      height: '200px',
      display: 'flex',
      alignItems: 'flex-end',
      gap: '1rem',
      padding: '0.5rem 0'
    },
    barWrapper: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      gap: '0.5rem'
    },
    bar: (height, color) => ({
      width: '100%',
      height: `${height}px`,
      background: color,
      borderRadius: '8px',
      transition: 'height 0.5s ease',
      cursor: 'pointer'
    }),
    barLabel: {
      fontSize: '0.6rem',
      color: '#64748b',
      textAlign: 'center'
    },
    legend: {
      display: 'flex',
      justifyContent: 'center',
      gap: '1.5rem',
      marginTop: '1rem',
      flexWrap: 'wrap'
    },
    legendItem: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      fontSize: '0.7rem',
      color: '#64748b'
    },
    legendColor: (color) => ({
      width: '12px',
      height: '12px',
      background: color,
      borderRadius: '3px'
    }),
    twoColumnGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '1.5rem',
      marginBottom: '1.5rem'
    },
    funnelContainer: {
      marginTop: '1rem'
    },
    funnelStep: {
      display: 'flex',
      alignItems: 'center',
      marginBottom: '0.5rem',
      padding: '0.5rem',
      background: '#f8fafc',
      borderRadius: '12px'
    },
    funnelStage: {
      width: '140px',
      fontSize: '0.75rem',
      fontWeight: '500',
      color: '#1e293b'
    },
    funnelBar: (percentage, color) => ({
      flex: 1,
      height: '8px',
      background: color,
      borderRadius: '4px',
      width: `${percentage}%`,
      transition: 'width 0.5s ease'
    }),
    funnelCount: {
      width: '60px',
      textAlign: 'right',
      fontSize: '0.8rem',
      fontWeight: '600',
      color: '#1e293b'
    },
    funnelPercentage: {
      width: '50px',
      textAlign: 'right',
      fontSize: '0.7rem',
      color: '#64748b'
    },
    downloadBtn: {
      padding: '0.4rem 0.8rem',
      background: '#7c3aed',
      color: 'white',
      border: 'none',
      borderRadius: '8px',
      fontSize: '0.7rem',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: '0.25rem',
      transition: 'all 0.2s ease'
    },
    downloadBtnDisabled: {
      padding: '0.4rem 0.8rem',
      background: '#94a3b8',
      color: 'white',
      border: 'none',
      borderRadius: '8px',
      fontSize: '0.7rem',
      cursor: 'not-allowed',
      display: 'flex',
      alignItems: 'center',
      gap: '0.25rem',
      opacity: 0.6
    }
  }

  if (loading) {
    return (
      <div style={styles.container}>
        <div style={{ textAlign: 'center', padding: '3rem' }}>
          <div style={{ width: '2rem', height: '2rem', border: '3px solid #e2e8f0', borderTopColor: '#7c3aed', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 1rem' }}></div>
          <p style={{ color: '#64748b' }}>Loading analytics...</p>
          <style>{`
            @keyframes spin {
              to { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      </div>
    )
  }

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <div style={styles.title}>
          <BarChart3 size={22} color="#7c3aed" />
          <span>Placement Analytics</span>
          <span style={{ 
            fontSize: '0.7rem', 
            color: '#64748b', 
            background: '#f1f5f9',
            padding: '0.15rem 0.6rem',
            borderRadius: '20px'
          }}>
            {stats.totalApplications} Applications
          </span>
        </div>
        <button 
          onClick={downloadReport} 
          disabled={downloading}
          style={downloading ? styles.downloadBtnDisabled : styles.downloadBtn}
        >
          <FileDown size={14} /> {downloading ? 'Downloading...' : 'Download Report'}
        </button>
      </div>

      <div style={styles.statsGrid}>
        <div style={styles.statCard('#3b82f6')}>
          <div style={styles.statValue}>{stats.totalApplications}</div>
          <div style={styles.statLabel}>Total Applications</div>
        </div>
        <div style={styles.statCard('#10b981')}>
          <div style={styles.statValue}>{stats.shortlisted}</div>
          <div style={styles.statLabel}>Shortlisted</div>
        </div>
        <div style={styles.statCard('#8b5cf6')}>
          <div style={styles.statValue}>{stats.offersSent}</div>
          <div style={styles.statLabel}>Offers Sent</div>
        </div>
        <div style={styles.statCard('#f59e0b')}>
          <div style={styles.statValue}>{stats.hiringRate}%</div>
          <div style={styles.statLabel}>Hiring Rate</div>
        </div>
      </div>

      <div style={styles.chartCard}>
        <div style={styles.chartHeader}>
          <div style={styles.chartTitle}>
            <TrendingUp size={16} color="#7c3aed" />
            <span>Application Trends</span>
          </div>
          <div style={styles.tabsContainer}>
            <button onClick={() => setChartType('applications')} style={styles.tab(chartType === 'applications')}>Applications</button>
            <button onClick={() => setChartType('shortlisted')} style={styles.tab(chartType === 'shortlisted')}>Shortlisted</button>
            <button onClick={() => setChartType('selected')} style={styles.tab(chartType === 'selected')}>Selected</button>
          </div>
        </div>
        <div style={styles.chartContainer}>
          {monthlyData.months.map((month, idx) => {
            const value = chartType === 'applications'
              ? monthlyData.applications[idx]
              : chartType === 'shortlisted'
                ? monthlyData.shortlisted[idx]
                : monthlyData.selected[idx]
            const color = chartType === 'applications'
              ? '#3b82f6'
              : chartType === 'shortlisted'
                ? '#10b981'
                : '#8b5cf6'
            return (
              <div key={month} style={styles.barWrapper}>
                <div style={styles.bar(getBarHeight(value), color)} title={`${value} ${chartType}`}></div>
                <div style={styles.barLabel}>{month}</div>
              </div>
            )
          })}
        </div>
        <div style={styles.legend}>
          <div style={styles.legendItem}><div style={styles.legendColor('#3b82f6')}></div><span>Applications</span></div>
          <div style={styles.legendItem}><div style={styles.legendColor('#10b981')}></div><span>Shortlisted</span></div>
          <div style={styles.legendItem}><div style={styles.legendColor('#8b5cf6')}></div><span>Selected</span></div>
        </div>
      </div>

      <div style={styles.twoColumnGrid}>
        <div style={styles.chartCard}>
          <div style={styles.chartTitle}>
            <Users size={16} color="#7c3aed" />
            <span>Branch Wise Distribution</span>
          </div>
          {branchData.length === 0 ? (
            <p style={{ textAlign: 'center', color: '#64748b', padding: '1rem 0' }}>No branch data available</p>
          ) : (
            branchData.map(branch => (
              <div key={branch.name} style={{ marginBottom: '0.75rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.25rem' }}>
                  <span style={{ fontSize: '0.75rem', fontWeight: '500' }}>{branch.name}</span>
                  <span style={{ fontSize: '0.7rem', color: '#64748b' }}>{branch.count} ({branch.percentage}%)</span>
                </div>
                <div style={{ width: '100%', height: '6px', background: '#e2e8f0', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ width: `${branch.percentage}%`, height: '100%', background: branch.color, borderRadius: '3px' }}></div>
                </div>
              </div>
            ))
          )}
        </div>

        <div style={styles.chartCard}>
          <div style={styles.chartTitle}>
            <Award size={16} color="#7c3aed" />
            <span>Package Distribution</span>
          </div>
          {packageData.length === 0 ? (
            <p style={{ textAlign: 'center', color: '#64748b', padding: '1rem 0' }}>No package data available</p>
          ) : (
            packageData.map(pkg => (
              <div key={pkg.range} style={{ marginBottom: '0.75rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.25rem' }}>
                  <span style={{ fontSize: '0.75rem', fontWeight: '500' }}>{pkg.range}</span>
                  <span style={{ fontSize: '0.7rem', color: '#64748b' }}>{pkg.count} offers</span>
                </div>
                <div style={{ width: '100%', height: '6px', background: '#e2e8f0', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{ width: `${(pkg.count / (pkg.maxCount || 100)) * 100}%`, height: '100%', background: pkg.color, borderRadius: '3px' }}></div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      <div style={styles.chartCard}>
        <div style={styles.chartTitle}>
          <Target size={16} color="#7c3aed" />
          <span>Hiring Funnel</span>
        </div>
        <div style={styles.funnelContainer}>
          {hiringFunnel.length === 0 ? (
            <p style={{ textAlign: 'center', color: '#64748b', padding: '1rem 0' }}>No hiring data available</p>
          ) : (
            hiringFunnel.map((stage) => (
              <div key={stage.stage} style={styles.funnelStep}>
                <div style={styles.funnelStage}>{stage.stage}</div>
                <div style={{ flex: 1, marginRight: '1rem' }}>
                  <div style={{ width: '100%', height: '8px', background: '#e2e8f0', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={styles.funnelBar(stage.percentage, stage.color)}></div>
                  </div>
                </div>
                <div style={styles.funnelCount}>{stage.count}</div>
                <div style={styles.funnelPercentage}>{stage.percentage}%</div>
              </div>
            ))
          )}
        </div>
      </div>

      <div style={{ ...styles.chartCard, background: 'linear-gradient(135deg, #ede9fe, #f3e8ff)' }}>
        <div style={styles.chartTitle}>
          <Zap size={16} color="#7c3aed" />
          <span>Key Insights</span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginTop: '0.5rem' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: '#5b21b6' }}>{insights.applicationGrowth}</div>
            <div style={{ fontSize: '0.65rem', color: '#6d28d9' }}>Application Growth</div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: '#5b21b6' }}>{insights.topBranchPercentage}%</div>
            <div style={{ fontSize: '0.65rem', color: '#6d28d9' }}>{insights.topBranch} Students</div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: '#5b21b6' }}>{insights.highestPackage}</div>
            <div style={{ fontSize: '0.65rem', color: '#6d28d9' }}>Highest Package</div>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  )
}

export default Analytics